### ISSUE TITLE
Syntax error in `extract_gridded_RCM_data.py`

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/Antarctica_Today#9]
@mmacferrin thoughts on what this should look like? Found this with a static analysis tool. I believe this code isn't needed for our current objectives, but good to document the finding anyway :) 

https://github.com/nsidc/Antarctica_Today/blob/4cc5601bee494a0c51c3a1453a3f262f977e34d9/src/src_baseline/extract_gridded_RCM_data.py#L18

```
          File "src/src_baseline/extract_gridded_RCM_data.py", line 18
            netCDF4.
                    ^                                                                                                                          
        SyntaxError: invalid syntax  
```

**Comment by mmacferrin** [comment]
Or, yes, if you just want to comment out that line, go ahead. I'm realizing now, this was work that was originally used to get "average annual temperatures", which was a field that the passive-microwave models needed. We were going to get that from an RCM (which this code was going), but decided instead to pull it from a re-gridded version of firn measurements instead. Obviously, I got halfway through a code line before getting distracted, eventually abandoned this file, and then checked-it in without reviewing it again. Just sloppy management on my part.

**Comment by mmacferrin** [comment]
So again, yes, you can delete the file, either way.

**Comment by MattF-NSIDC** [comment]
>Or, yes, if you just want to comment out that line, go ahead

I'm just commenting for now to get some tools running correctly, I think long-term the resolution to this issue is to remove the file, since it's not needed. As you say we can always restore anything we break! :rocket:

**Comment by mmacferrin** [comment]
We can discuss in more detail in the future. Especially with respect to the "baseline_datasets" code modules, a lot of that code isn't specifically needed to generate any of the "daily melt" plots the NSIDC creates now, and thus aren't "necessary" to the operation of the code. But they *were* used to create the necessary data fields (ice mask, mean annual temperature, elevation) that Tom Mote needed to create the initial version of his passive microwave model for Antarctica, upon which the "annual threshold" .bin files are based. And as such, we'd want to keep them, as they were essential to the original product. This one in particular isn't (I don't think), but some of the others are essential to the original creation. Anyway, just putting this in here for context and background.

**Comment by MattF-NSIDC** [comment]
> And as such, we'd want to keep them, as they were essential to the original product. This one in particular isn't (I don't think), but some of the others are essential to the original creation. Anyway, just putting this in here for context and background.

This is really useful information. I think we need to get a documentation page started about this :)
